version: '3'

services:
  dbt_fiera:  # Este es el nombre de tu servicio
    build: .
    image: dbt-image  # El nombre que tendr√° la imagen
    volumes:
      - .:/usr/app  # <--- MAGIA: Lo que edites en VS Code aparece en el contenedor
    environment:
      - DBT_PROFILES_DIR=/usr/app