[project]
name = "project_dbt"
version = "0.1.0"
description = "Proyecto Personal"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.0.0",
    "dbt-duckdb>=1.9.6",
    "harlequin>=2.4.1",
]
